/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const App = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'hindiName' : IDL.Text,
  'category' : IDL.Text,
});
export const Preferences = IDL.Record({
  'wallpaper' : IDL.Text,
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  'addApp' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'closeApp' : IDL.Func([], [], []),
  'getAllApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'getAppUsage' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getOpenApp' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getPreferences' : IDL.Func([], [Preferences], ['query']),
  'openAppById' : IDL.Func([IDL.Nat], [], []),
  'updatePreferences' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const App = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'hindiName' : IDL.Text,
    'category' : IDL.Text,
  });
  const Preferences = IDL.Record({
    'wallpaper' : IDL.Text,
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    'addApp' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'closeApp' : IDL.Func([], [], []),
    'getAllApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'getAppUsage' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getOpenApp' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getPreferences' : IDL.Func([], [Preferences], ['query']),
    'openAppById' : IDL.Func([IDL.Nat], [], []),
    'updatePreferences' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };